export const fakeData = [
  {
    id: 1,
    alt: "Product description",
    src: "/assets/products/image (1).png",
    width: 380,
    height: 380,
    text: "ID:01",
  },
  {
    id: 2,
    alt: "Product description",
    src: "/assets/products/image (2).png",
    width: 380,
    height: 380,
    text: "ID:02",
  },
  {
    id: 3,
    alt: "Product description",
    src: "/assets/products/image (3).png",
    width: 380,
    height: 380,
    text: "ID:03",
  },
  {
    id: 4,
    alt: "Product description",
    src: "/assets/products/image (4).png",
    width: 380,
    height: 380,
    text: "ID:04",
  },
  {
    id: 5,
    alt: "Product description",
    src: "/assets/products/image (5).png",
    width: 380,
    height: 380,
    text: "ID:05",
  },
  {
    id: 6,
    alt: "Product description",
    src: "/assets/products/image (6).png",
    width: 380,
    height: 380,
    text: "ID:06",
  },
  {
    id: 7,
    alt: "Product description",
    src: "/assets/products/image (7).png",
    width: 380,
    height: 380,
    text: "ID:07",
  },
  {
    id: 8,
    alt: "Product description",
    src: "/assets/products/image (8).png",
    width: 380,
    height: 380,
    text: "ID:08",
  },
  {
    id: 9,
    alt: "Product description",
    src: "/assets/products/image (9).png",
    width: 380,
    height: 380,
    text: "ID:09",
  },
  {
    id: 10,
    alt: "Product description",
    src: "/assets/products/image (10).png",
    width: 380,
    height: 380,
    text: "ID:010",
  },
  {
    id: 11,
    alt: "Product description",
    src: "/assets/products/image (11).png",
    width: 380,
    height: 380,
    text: "ID:011",
  },
  {
    id: 12,
    alt: "Product description",
    src: "/assets/products/image (12).png",
    width: 380,
    height: 380,
    text: "ID:012",
  },
  {
    id: 13,
    alt: "Product description",
    src: "/assets/products/image (13).png",
    width: 380,
    height: 380,
    text: "ID:013",
  },
  {
    id: 14,
    alt: "Product description",
    src: "/assets/products/image (14).png",
    width: 380,
    height: 380,
    text: "ID:014",
  },
];
